---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(mgcv)
library(tidyverse)
```

```{r, echo=T,tidy=F, include=T, message=FALSE,highlight=TRUE}
richness_ti_model = gam(richness ~ s(Longitude,Latitude)+s(Year) + 
                          ti(Longitude, Latitude, Year, d=c(2,1)),
                          data=florida_birds,family=poisson,method="REML")
layout(matrix(1:2,ncol=2))
plot(richness_ti_model,scheme=2)
layout(1)
summary(richness_ti_model)
```


```{r, echo=T,tidy=F, include=T, message=FALSE,highlight=TRUE}
pacman::p_load(gamm4)
library(gamm4)
set.seed(0)
dat <- gamSim(1,n=400,scale=2) ## simulate 4 term additive truth
## Now add 20 level random effect `fac'...
dat$fac <- fac <- as.factor(sample(1:20,400,replace=TRUE))
dat$y <- dat$y + model.matrix(~fac-1)%*%rnorm(20)*.5

br <- gamm4(y~s(x0)+x1+s(x2),data=dat,random=~(1|fac))
plot(br$gam,pages=1)
```

```{r, echo=T,tidy=F, include=T, message=FALSE,highlight=TRUE}
pacman::p_load(gamm4)
library(gamm4)
set.seed(0)
dat <- gamSim(1,n=400,scale=2) ## simulate 4 term additive truth
## Now add 20 level random effect `fac'...
dat$fac <- fac <- as.factor(sample(1:20,400,replace=TRUE))
dat$y <- dat$y + model.matrix(~fac-1)%*%rnorm(20)*.5

mod <- gamm4(summed_count_spores ~ s(distance_m)+s(degrees),
            random=~(1|field), family=poisson, 
            data=heat_dat, subset = time_min==90)
plot(br$gam,pages=1)
```
