<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Fit GAM model of spore counts</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Peanut Smut Spore Dispersal Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fas fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="data_import.html">
    <span class="fas fa-table"></span>
     
    Data Import
  </a>
</li>
<li>
  <a href="data_viz.html">
    <span class="fas fa-chart-area"></span>
     
    Data Visualization
  </a>
</li>
<li>
  <a href="gam_model.html">
    <span class="fas fa-file-code"></span>
     
    Model Fitting
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/juanchiem/peanut_smut_aerial">
    <span class="fa fa-github-square"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Fit GAM model of spore counts</h1>

</div>


<div id="load-libraries" class="section level2">
<h2>Load libraries</h2>
<pre class="r"><code>library(&quot;tidyverse&quot;)
library(&quot;ggpubr&quot;)
library(&quot;gratia&quot;)
library(&quot;here&quot;)
library(&quot;mgcv&quot;)
library(&quot;DHARMa&quot;)
theme_set(theme_pubclean())</code></pre>
</div>
<div id="spore-proportion-chi-squared-analysis" class="section level2">
<h2>Spore proportion chi-squared analysis</h2>
<p>Check if the spore type, number of nuclei, affects the dispersal.</p>
<p>Using the default <code>chisq.test()</code> will result in a warning
due to small expected values meaning that approximations of p may not be
correct.
<code>Warning message: In chisq.test(.) : Chi-squared approximation may be incorrect</code>
Therefore, we will use Monte Carlo simulation to simulate p values.</p>
<p>(Manuscript’s section <code>Results/3.2</code>)</p>
<pre class="r"><code>set.seed(3)
x &lt;- read_csv(here(&quot;data/spore_type.csv&quot;),
              show_col_types = FALSE) %&gt;%
  group_by(meter, spore_nuclei) %&gt;%
  summarise(n = sum(count), .groups = &#39;drop&#39;) %&gt;%
  spread(spore_nuclei, n) %&gt;%
  column_to_rownames(&#39;meter&#39;) %&gt;%
  chisq.test(simulate.p.value = TRUE) </code></pre>
<p>The major spore type spread expected was the individual spore having
a smaller spore size (18.8 µm); however, no statistical differences were
recorded in spore type proportion at 100 m to 400 m downwind (P =
0.195902, X-squared = 20.6561456).</p>
</div>
<div id="spore-dispersal-gam-model" class="section level2">
<h2>Spore dispersal GAM Model</h2>
<p>(Manuscript’s section <code>Results/3.3</code>)</p>
<div id="load-data" class="section level3">
<h3>Load data</h3>
<pre class="r"><code>load(here(&quot;data/mod_dat.Rdata&quot;))

sdp_dat &lt;- read_csv(here(&quot;data/sdp_data.csv&quot;),
                    show_col_types = FALSE,
                    col_types = list(field = col_factor())) %&gt;%
  arrange(field) %&gt;%
  select(field, inc, SDP, DSI) %&gt;%
  mutate(field = as.factor(field))

# summarise SDP index by field and create a binomial variable w/ cutoff @ 5 ----

ps_inc &lt;-
  sdp_dat %&gt;% 
  group_by(field) %&gt;%
  summarise(SDP = mean(SDP))

mod_dat &lt;- left_join(mod_dat, ps_inc, by = c(&quot;field&quot;))</code></pre>
</div>
<div id="inspect-the-mod_dat-object" class="section level3">
<h3>Inspect the mod_dat object</h3>
<pre class="r"><code>mod_dat %&gt;% # str
  distinct(field, trap_coord, .keep_all = TRUE) %&gt;%
  select(trap_coord,
         trap_degrees,
         degree_dif,
         wind_degrees,
         wind_speed,
         distance_m,
         SDP,
         n_spore) %&gt;%
  print(n = Inf)</code></pre>
<pre><code>## # A tibble: 24 x 9
## # Groups:   field [6]
##    field trap_coord trap_degrees degree_dif wind_degrees wind_speed distance_m
##    &lt;fct&gt; &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 1     N                     0    -76.2          76.2        1.49        100
##  2 1     E                    90     13.8          76.2        1.49        100
##  3 1     W                   270    194.           76.2        1.49        100
##  4 1     S                   180    104.           76.2        1.49        100
##  5 2     N                     0   -201.          201.         7.27        100
##  6 2     E                    90   -111.          201.         7.27        100
##  7 2     W                   270     68.7         201.         7.27        100
##  8 2     S                   180    -21.3         201.         7.27        100
##  9 3     NE                   45    -90.3         135.         2.93        100
## 10 3     SE                  135     -0.313       135.         2.93        100
## 11 3     NW                  315    180.          135.         2.93        100
## 12 3     SW                  225     89.7         135.         2.93        100
## 13 4     N                     0    -35.9          35.9        3.90        100
## 14 4     E                    90     54.1          35.9        3.90        100
## 15 4     W                   270    234.           35.9        3.90        100
## 16 4     S                   180    144.           35.9        3.90        100
## 17 5     NE                   45     15.1          29.9        3.92        100
## 18 5     SE                  135    105.           29.9        3.92        100
## 19 5     NW                  315    285.           29.9        3.92        100
## 20 5     SW                  225    195.           29.9        3.92        100
## 21 6     N                     0     -2.16          2.16       7.57        100
## 22 6     E                    90     87.8           2.16       7.57        100
## 23 6     W                   270    268.            2.16       7.57        100
## 24 6     S                   180    178.            2.16       7.57        100
## # i 2 more variables: SDP &lt;dbl&gt;, n_spore &lt;dbl&gt;</code></pre>
<p>Based on the use of AIC to evaluate model fit to the data, the
following GAM best fit the data with the smoothed time slice variables,
s(<code>time_slice</code>); a smoothed term for the the distance of the
traps from the field and wind speed,
<code>s(distance_m, wind_speed)</code>; a smoothed term for the severely
damaged pods, <code>s(SDP)</code> and the field and traps themselves as
a smoothed term random effect, <code>s(field</code>, <code>xy</code>)
using a negative binomial family, <code>nb()</code>.</p>
<pre class="r"><code># create a factor for the trap locations in Cartesian coords to be used as a random effect
mod_dat$xy &lt;- as.factor(paste(mod_dat$x, mod_dat$y))

m1 &lt;- gam(
  n_spore ~ s(time_slice, k = 3) +
    s(distance_m, wind_speed, k = 50) +
    s(SDP, k = 6) +
    s(field, xy, bs = &quot;re&quot;),
  data = mod_dat,
  select = TRUE,
  method = &quot;REML&quot;,
  family = nb()
)</code></pre>
</div>
<div id="inspect-model-m1" class="section level3">
<h3>Inspect Model m1</h3>
<pre class="r"><code>summary(m1)</code></pre>
<pre><code>## 
## Family: Negative Binomial(2.483) 
## Link function: log 
## 
## Formula:
## n_spore ~ s(time_slice, k = 3) + s(distance_m, wind_speed, k = 50) + 
##     s(SDP, k = 6) + s(field, xy, bs = &quot;re&quot;)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   2.1871     0.1841   11.88   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                              edf Ref.df  Chi.sq p-value    
## s(time_slice)             0.9730      2   37.28  &lt;2e-16 ***
## s(distance_m,wind_speed)  1.4980     48 1221.93  0.0171 *  
## s(SDP)                    0.7341      5  620.54  0.0576 .  
## s(field,xy)              86.1747     95 1204.66  &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.739   Deviance explained = 89.2%
## -REML = 1073.2  Scale est. = 1         n = 288</code></pre>
<div id="check-model-m1" class="section level4">
<h4>Check model m1</h4>
<pre class="r"><code>gam.check(m1)</code></pre>
<p><img src="gam_model_files/figure-html/gam-check-m1-1.png" width="60%" /></p>
<pre><code>## 
## Method: REML   Optimizer: outer newton
## full convergence after 11 iterations.
## Gradient range [-0.0002416798,0.0002309939]
## (score 1073.208 &amp; scale 1).
## Hessian positive definite, eigenvalue range [5.501528e-06,53.4399].
## Model rank =  249 / 249 
## 
## Basis dimension (k) checking results. Low p-value (k-index&lt;1) may
## indicate that k is too low, especially if edf is close to k&#39;.
## 
##                               k&#39;     edf k-index p-value
## s(time_slice)              2.000   0.973    0.96    0.50
## s(distance_m,wind_speed)  49.000   1.498    1.01    0.92
## s(SDP)                     5.000   0.734    0.93    0.35
## s(field,xy)              192.000  86.175      NA      NA</code></pre>
<pre class="r"><code>summary(m1)</code></pre>
<pre><code>## 
## Family: Negative Binomial(2.483) 
## Link function: log 
## 
## Formula:
## n_spore ~ s(time_slice, k = 3) + s(distance_m, wind_speed, k = 50) + 
##     s(SDP, k = 6) + s(field, xy, bs = &quot;re&quot;)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   2.1871     0.1841   11.88   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##                              edf Ref.df  Chi.sq p-value    
## s(time_slice)             0.9730      2   37.28  &lt;2e-16 ***
## s(distance_m,wind_speed)  1.4980     48 1221.93  0.0171 *  
## s(SDP)                    0.7341      5  620.54  0.0576 .  
## s(field,xy)              86.1747     95 1204.66  &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.739   Deviance explained = 89.2%
## -REML = 1073.2  Scale est. = 1         n = 288</code></pre>
<pre class="r"><code>vis.gam(
  m1,
  theta = 50,
  view = c(&quot;time_slice&quot;, &quot;SDP&quot;),
  ticktype = &quot;detailed&quot;,
  main = &quot;Time slice (minutes) and severely damaged pods (SDP)&quot;
)</code></pre>
<p><img src="gam_model_files/figure-html/gam-check-m1-2.png" width="60%" /></p>
<pre class="r"><code>vis.gam(
  m1,
  view = c(&quot;distance_m&quot;, &quot;wind_speed&quot;),
  theta = 50,
  ticktype = &quot;detailed&quot;,
  main = &quot;Trap distance from field (m) and wind speed (m/s)&quot;
)</code></pre>
<p><img src="gam_model_files/figure-html/gam-check-m1-3.png" width="60%" /></p>
<pre class="r"><code>plot(m1)</code></pre>
<p><img src="gam_model_files/figure-html/gam-check-m1-4.png" width="60%" /><img src="gam_model_files/figure-html/gam-check-m1-5.png" width="60%" /><img src="gam_model_files/figure-html/gam-check-m1-6.png" width="60%" /><img src="gam_model_files/figure-html/gam-check-m1-7.png" width="60%" /></p>
<pre class="r"><code># check residuals using DHARMa
simulateResiduals(m1, plot = TRUE)</code></pre>
<p><img src="gam_model_files/figure-html/gam-check-m1-8.png" width="60%" /></p>
<pre><code>## Object of Class DHARMa with simulated residuals based on 250 simulations with refit = FALSE . See ?DHARMa::simulateResiduals for help. 
##  
## Scaled residual values: 0.5966348 0.326032 0.8509289 0.7496079 0.5238095 0.1691754 0.6283619 0.8696426 0.4010286 0.0693676 0.9301913 0.7374863 0.644 0.8741518 0.1604343 0.01793573 0.6495237 0.3167456 0.4143331 0.5420092 ...</code></pre>
<p>The model fully converged after 11 iterations. All of the predictive
factors included were significant at <em>P</em> &gt; 0.1 and the model
had an adjusted R2 value of 0.726.</p>
<p>The <code>gam.check()</code> residuals show a slight pattern in the
Residuals vs. linear predicted values, but this is to be expected with
the zero values and negative binomial family, <code>nb()</code>, that
was used to fit the model. The QQ-plot appears to be reasonable as does
the histogram of residuals, and Response vs Fitted Values. To further
check the model’s fitness, there is a slight pattern in the DHARMa
residuals, but nothing to worry about too much in a small data set like
this while this QQ-plot and the associated tests all pass.</p>
<p>In all, this model looks to explain the spore dispersal data well
enough for this data set.</p>
</div>
<div id="check-for-autocorrelation" class="section level4">
<h4>Check for autocorrelation</h4>
<p>Because the data represent spatially and temporally correlated data,
it’s best to check for any autocorrelation in the residuals.</p>
<pre class="r"><code>acf(residuals(m1))</code></pre>
<p><img src="gam_model_files/figure-html/gam-autocorrelation-1.png" width="60%" /></p>
<pre class="r"><code>pacf(residuals(m1))</code></pre>
<p><img src="gam_model_files/figure-html/gam-autocorrelation-2.png" width="60%" /></p>
<p>This looks OK. There is no major pattern discernible in the ACF or
PACF plots that show cause for concern.</p>
</div>
</div>
<div
id="predict-spore-dispersal-and-visualise-spore-dispersal-predictions"
class="section level3">
<h3>Predict spore dispersal and visualise spore dispersal
predictions</h3>
<pre class="r"><code>dist &lt;- seq(100, 400, by = 100)

newd &lt;- expand_grid(
  wind_speed = 1:10,
  SDP = seq(from = 0.5, to = 10, by = 0.5),
  time_slice = unique(mod_dat$time_slice),
  distance_m = unique(mod_dat$distance_m),
  xy = unique(mod_dat$xy),
  field = 1
)

newd$pred_n_spore &lt;-
  predict(
    object = m1,
    newd,
    type = &quot;response&quot;,
    exclude = c(&quot;field&quot;, &quot;xy&quot;)
  )</code></pre>
<p>Visualize the spore dispersal predictions for traps at 100 m, 200 m,
300 m, 400 m around the harvest field for sampling times at 90, 180 and
270 minutes after harvest started.</p>
<pre class="r"><code>predictions &lt;-
  newd %&gt;%
  ggplot(aes(x = as.factor(distance_m), y = pred_n_spore)) +
  geom_boxplot() +
  labs(x = &quot;Distance from harvesting field (m)&quot;,
       y = &quot;Predicted Spores (n)&quot;)

predictions</code></pre>
<p><img src="gam_model_files/figure-html/graph-predictions-1.png" width="60%" /></p>
<pre class="r"><code>ggsave(
  predictions,
  file = &quot;plots_manuscript/spore_prediction.png&quot;,
  w = 5,
  h = 2,
  scale = 1.2
)</code></pre>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
